# -*- coding: utf-8 -*-
"""mood_movie_recommender.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tvSlnxCVpdHNZ73bWMLtZvqEpobIjZSQ
"""

!pip install scikit-learn pandas numpy requests -q

import pandas as pd
import numpy as np
import zipfile, urllib.request, os
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import TfidfVectorizer
import warnings
warnings.filterwarnings('ignore')
print('✅ Libraries loaded!')

url = 'https://files.grouplens.org/datasets/movielens/ml-latest-small.zip'
urllib.request.urlretrieve(url, 'ml-latest-small.zip')

with zipfile.ZipFile('ml-latest-small.zip', 'r') as z:
    z.extractall('.')

print('✅ Dataset downloaded!')
print(os.listdir('ml-latest-small'))

movies  = pd.read_csv('ml-latest-small/movies.csv')
ratings = pd.read_csv('ml-latest-small/ratings.csv')

print(f'Movies  : {movies.shape[0]} rows')
print(f'Ratings : {ratings.shape[0]} rows')
movies.head()

movies['genres_clean'] = movies['genres'].str.replace('|', ' ', regex=False)
movies['genres_list']  = movies['genres'].str.split('|')


movies['year'] = movies['title'].str.extract(r'\((\d{4})\)').astype(float)


avg = ratings.groupby('movieId')['rating'].agg(['mean','count']).reset_index()
avg.columns = ['movieId', 'avg_rating', 'num_ratings']

movies = movies.merge(avg, on='movieId', how='left')
movies['avg_rating']  = movies['avg_rating'].fillna(0)
movies['num_ratings'] = movies['num_ratings'].fillna(0)

print('✅ Preprocessing done!')
movies[['title','genres_clean','avg_rating','num_ratings']].head()

tfidf = TfidfVectorizer(stop_words='english')
tfidf_matrix = tfidf.fit_transform(movies['genres_clean'].fillna(''))

print(f'✅ TF-IDF Matrix shape: {tfidf_matrix.shape}')

MOOD_GENRE_MAP = {
    'happy'     : 'Comedy Animation Family Musical',
    'sad'       : 'Drama Romance Biography',
    'excited'   : 'Action Adventure Thriller SciFi',
    'scared'    : 'Horror Mystery Thriller',
    'romantic'  : 'Romance Drama Comedy',
    'angry'     : 'Action Crime Thriller',
    'bored'     : 'Adventure Fantasy SciFi Action',
    'nostalgic' : 'Animation Drama Family Classic',
    'motivated' : 'Biography Sport Drama History',
    'stressed'  : 'Comedy Animation Fantasy Family',
    'curious'   : 'Documentary Mystery SciFi History',
    'lonely'    : 'Romance Drama Comedy Animation',
    'chill'     : 'Comedy Documentary Animation Music',
}

print('🎭 Available moods:')
print(list(MOOD_GENRE_MAP.keys()))

def recommend(mood, top_n=10, min_ratings=30):
    mood = mood.lower().strip()

    if mood not in MOOD_GENRE_MAP:
        print(f'❌ Mood "{mood}" not found. Choose from: {list(MOOD_GENRE_MAP.keys())}')
        return


    mood_vec   = tfidf.transform([MOOD_GENRE_MAP[mood]])
    sim_scores = cosine_similarity(mood_vec, tfidf_matrix).flatten()

    df = movies.copy()
    df['mood_score'] = sim_scores


    df = df[df['num_ratings'] >= min_ratings].copy()


    max_r = df['avg_rating'].max() or 1
    df['final_score'] = (0.7 * df['mood_score']) + (0.3 * df['avg_rating'] / max_r)

    top = df.sort_values('final_score', ascending=False).head(top_n)

    print(f'\n🎬 Top {top_n} movies for mood: "{mood}"')
    print('='*60)
    for i, (_, row) in enumerate(top.iterrows(), 1):
        print(f"{i:2}. {row['title'][:45]:<45} ⭐ {row['avg_rating']:.1f}  ({int(row['num_ratings'])} ratings)")
        print(f"    Genres: {row['genres']}")
        print()

print('✅ Recommendation function ready!')

recommend('happy', top_n=10)

recommend('excited', top_n=10)

recommend('sad', top_n=10)

mood_input = input('Enter your mood: ')
recommend(mood_input, top_n=10)

import matplotlib.pyplot as plt

def plot_mood_genres(mood):
    mood = mood.lower().strip()
    if mood not in MOOD_GENRE_MAP:
        print('Mood not found'); return

    mood_vec   = tfidf.transform([MOOD_GENRE_MAP[mood]])
    sim_scores = cosine_similarity(mood_vec, tfidf_matrix).flatten()
    df = movies.copy()
    df['mood_score'] = sim_scores
    df = df[df['num_ratings'] >= 30]
    top = df.sort_values('mood_score', ascending=False).head(20)

    all_genres = [g for sublist in top['genres_list'].dropna() for g in sublist]
    genre_counts = pd.Series(all_genres).value_counts().head(10)

    plt.figure(figsize=(10, 5))
    genre_counts.plot(kind='barh', color='steelblue')
    plt.title(f'Top Genres for Mood: "{mood}"', fontsize=14)
    plt.xlabel('Count')
    plt.gca().invert_yaxis()
    plt.tight_layout()
    plt.show()

plot_mood_genres('motivated')